### ISSUE TITLE
Create docker and docker-compose files for development

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#126]
Opening the api server in one window and the client server in another window is cumbersome, along with remembering to do things like `yarn install`, `pip install --lots-of-stuff`, etc.

- Should we create docker/-compose to make this automated and contained?
- How does anyone feel about using docker in production? (see #127)

**Comment by willfulbard** [comment]
@Alig1493  - If you need to `docker-compose down` an individual service, yeah, I guess there isn't a way to stop that unless you use the separate docker-compose files, but it looks like you can get around the total reboot problem for at least rebuild.  Does the following seem like it might get around the issue you mentioned?

```
docker-compose up -d --no-deps --build web
```

- [--no-deps means don't start linked services](https://docs.docker.com/compose/reference/up/)
- web means only this service

I tried it with both `docker-compose up -d --no-deps --build web` and `docker-compose up -d --no-deps --build postgres` with novel changes to the docker-compose.yml, and it seemed to work to only rebuild and restart the web/postgres services individually.

**Comment by Alig1493** [comment]
@willfulbard Hey I just looked into what you said in a bit more depth and it really checks out. Might have been the projects of mine (personal and work related) had some other caveats where building and starting the containers without downtime didn't always behave as expected. But yes the command you gave works, even more than that I just read up we can just use `up` followed by `--build <service name>` and the changes should be registered and applied. I tried it by adding a new env on the fly and then `docker compose up --build -d web` and it was registered. 

So yes you can have them all in a single compose file and manage them from there no problem.

Thanks for looking into this I learned something new and interesting. Probably should have researched this a bit more myself haha.
