### ISSUE TITLE
create a user serializer

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#133]
We need user CRUD!

Currently in the following views, we're using a simple object when we return a user.  It would be way better if we could create an official way to serialize a user and return that.  This should have the added bonus of adding editing via POST, PUT, and DELETE

-  [LoginView](https://github.com/camphoric/camphoric/blob/main/server/camphoric/views.py#L50)
-  [LogoutView](https://github.com/camphoric/camphoric/blob/main/server/camphoric/views.py#L79)
-  [UserView](https://github.com/camphoric/camphoric/blob/main/server/camphoric/views.py#L87)

**Comment by brsaylor** [comment]
:+1:

**Comment by idelizer** [comment]
Created user serializer, along with user view set and urls.

Returns user(s) without passwords. Currently, users created without a password are set an unusable password. We want to be able to then send that user a link to set their password. Admins are able to edit details of other admins except for password. 

NEXT STEPS
1. finish tests 
2. create separate flow to handle passwords (endpoint for user to set password via email, endpoint for user to change password given current password)
3. LoginView and UserView to return serialized user object (call user serializer on user object) or return a 401 if no one is logged in

QUESTIONS
How does LogoutView need to change?
