### ISSUE TITLE
Create Paypal integration and payment option

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#147]
We want people to be able to pay by paypal or check.  We should have that integrated in, and probably have api endpoints that can use paypal's api

https://developer.paypal.com/docs/api/overview/

**Comment by brsaylor** [comment]
- make Payment.deposit nullable
- add Payment.type enum (check, paypal)

**Comment by brsaylor** [comment]
https://django-paypal.readthedocs.io/en/latest/overview.html

**Comment by willfulbard** [comment]
It's probably worth looking at the old PHP code as well.  The old code created this form:

https://github.com/willfulbard/harmony/blob/master/htdocs/regsummary.php#L90

If you are paying by paypal it changes the action and submits

https://github.com/willfulbard/harmony/blob/master/htdocs/regsummary.php#L72

You can see in the code that (at least the way it used to work) it used the paypal IPN to record the successful transaction:

https://github.com/willfulbard/harmony/blob/master/htdocs/data/paypalipn.php

https://developer.paypal.com/api/nvp-soap/ipn/

The link to docs in the django-paypal is out of date, but I found the relevent docs here:

https://developer.paypal.com/docs/checkout/standard/integrate/

it looks like it's all done via AJAX calls now, I'm not sure if this django-paypal module is the right course for us.

It does look like PayPal puts out a react library for integration with front-ends:

https://github.com/paypal/react-paypal-js

**Comment by bederber** [comment]
Created #234 to complete this work
