### ISSUE TITLE
Create interface for assigning lodging 

### ISSUE THREAD

**Issue by bederber** [camphoric/camphoric#215]

**Comment by bederber** [comment]
Look at hotel admin systems for ideas.
May be worth setting up a brainstorm session.

**Comment by willfulbard** [comment]
@brsaylor Do we need to differentiate between lodging requested and lodging assigned?  In other words, should these be two different data points, one field for what the user requested, and one that the camp admin assigned?

**Comment by willfulbard** [comment]
Adding some notes we made about different systems, per a meeting with @bederber and @elementswebsolutions 

https://miro.com/app/board/uXjVPfO7FXM=/
