### ISSUE TITLE
Confirmation Text for Lark Campout

### ISSUE THREAD

**Issue by millerlark** [camphoric/camphoric#241]
This should be the text on the confirmation page:

# You're all set!

## See you at Lark Campout 2022!

​​If you're paying by PayPal, we'll be sending you a confirmation with payment instructions within the next week. If you're paying by check, please make it for **\${{pricing_results.total}}**
payable to "Lark Traditional Arts", and mail it to:

Lark Traditional Arts
PO Box 1724
Mendocino, CA 95460
USA

Do you have questions? Email us at registration@larkcamp.org or call 707-397-5275

**Comment by millerlark** [comment]
And here is the text for the confirmation email:

const subject = 'Lark Campout 2022 Registration Confirmation';
const template = `
Dear {{registration.payment.payer_first_name}} {{registration.payment.payer_last_name}},
Your online registration for the Lark Campout 2022 has been received.
You have registered for:
| Name | Age | Tuition | Total |
| ---- | --- | ------- | ------- | ----- | ----- |
{{#campers}}
| {{first_name}} {{last_name}} | {{age}} |\${{pricing_result.tuition}} |\${{pricing_result.total}} |
{{/campers}}

Donation to Lark Traditional Arts - None Yet

TOTAL DUE: \${{pricing_results.total}}
Registration Number: 2022-{{ registration.id }}

You are signed up for {{Chore}}

​​You chose to pay by {{Check/PayPal}}

If you're paying by PayPal or credit card, we'll be sending you a confirmation with payment instructions within the next week. If you're paying by check, please make it for \${{pricing_results.total}} payable to "Lark Traditional Arts", and mail it to:

Lark Traditional Arts
PO Box 1724
Mendocino, CA 95460
USA

Do you have questions? Email us at registration@larkcamp.org or call 707-397-5275
`;

export default {
  confirmation_email_template: template,
  confirmation_email_subject: subject,
};

**Comment by willfulbard** [comment]
This has been fixed
