### ISSUE TITLE
Improve confirmation email formatting on mobile

### ISSUE THREAD

**Issue by brsaylor** [camphoric/camphoric#271]
The confirmation email doesn't render well on mobile (the table gets too narrow to fit all the content without excessive wrapping).
![40C92776-9737-45C5-951E-A49240B2AF1C](https://user-images.githubusercontent.com/15619556/188774319-7986b7fc-7181-4073-bbf4-8c934bde31c0.jpg)

![84AA0B89-6E9F-4CCE-89CA-E8810F974753](https://user-images.githubusercontent.com/15619556/188774338-16d10193-eb9e-41d3-8702-75a1043c3971.jpg)

**Comment by willfulbard** [comment]
We're going to change the formatting for this email but it might be worth looking into better html email templates in the future.
