### ISSUE TITLE
Scroll on Lodging page

### ISSUE THREAD

**Issue by millerlark** [camphoric/camphoric#344]
Please find a way for unassigned lodgers and lodging assignments to be scrolled independently.
Also, the "info" button is inaccessible in the lodger's list (left side list) when a camper's name is long.

**Comment by millerlark** [comment]
Upon a preliminary look at lodging this year, the scrolling issue makes it very difficult to assign lodging when there are a lot of unassigned campers. It's basically making it extremely difficult to assign specific lodging.

**Comment by willfulbard** [comment]
fixed in #497
