### ISSUE TITLE
Add Lodging options

### ISSUE THREAD

**Issue by millerlark** [camphoric/camphoric#356]
- [ ] I need a cook's cabin in camp 2 (I think it has 5 spaces)
- [ ] I also need a Cabin 34 and 35 in camp 2 (they are tent cabins, but that probably doesn't matter)
- [ ] I need 5 more 15-20' RV spaces in Camp 3 (and 5 less under 15')
- [ ] Maybe the same as above for Camp 1. It seems like some of the vans are over 15'

**Comment by willfulbard** [comment]
I did all but the camp 1 one, since you said "maybe"
