### ISSUE TITLE
Camp Harmony confirmation email text

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#415]
This is the format for the confirmation email that the PRIMARY registrant receives.  We have not sent emails to "added campers" in the past, so I think it'll be ok.  

Dear Judy Depenau,

Thank you for your online registration for Camp Harmony 2023-24! This email confirms the following:

Registration Info

Judy Depenau, Age 31
246 Benton St
Santa, Rosa 95401
707-694-7478, 707-523-3556
[jkdepenau@gmail.com](mailto:jkdepenau@gmail.com)
Meals: Vegetarian, No Gluten
Registered for Sun Dec 29th, Mon Dec 30th
Day of arrival: Sun Dec 29 at 2pm
Housing: Economy

------------

Judy Depenau Jr, Age 17
707-694-7478, 707-523-3556
[jkdepenau@gmail.com](mailto:jkdepenau@gmail.com)
Meals: Vegetarian, No Gluten
Registered for Sun Dec 29th, Mon Dec 30th
Day of arrival: Sun Dec 29 at 2pm
Housing: Economy

-------------

John Depenau, Age 31
707-694-7478, 707-523-3556
[jkdepenau@gmail.com](mailto:jkdepenau@gmail.com)
Meals: Vegetarian, No Gluten
Registered for Sun Dec 29th, Mon Dec 30th
Day of arrival: Sun Dec 29 at 2pm
Housing: Economy

-------------

Total Fees: $170.00

Campership Donation: $10

No other registrants entered

TOTAL FOR THIS REGISTRATION: $200.00

You have elected to pay by PayPal. Confirmation of your payment will be sent to the registrar as soon as your payment clears.

If you would like to sign up to lead a workshop, you may do so on the [Workshop Signup Thread] https://docs.google.com/forms/d/e/1FAIpQLSfe9LwY1nBqNPan8QE6lcndFJsTJpnTL3fbwK1BKFNsyumEWA/viewform?vc=0&c=0&w=1&flr=0 

You have agreed to Camp Harmony's Covid policy [link] and you will need to provide proof of a negative Covid test upon entering Camp.  

You will be receiving an email with your housing assignment and additional details by December 4. Thank you for registering for Camp Harmony!

**Comment by willfulbard** [comment]
Please edit this with the following in mind:

- Please indicate the workshop signup thread, or link to workshop signup instructions
- Please note that this form doesn't do renewals, please indicate what you want me to do put instead of that
- The system will only send ONE confirmation email out to the primary registrant.  Please indicate how you want to format the email for multiple registrants.

**Comment by bloomingbooks** [comment]
done

**Comment by CharlieFenton** [comment]
The confirmation email should reiterate that each person over 2 needs to bring proof of a negative COVID test, perhaps with the link to the COVID policy,
