### ISSUE TITLE
Camp Harmony: Etiquette document

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#419]
Please replace Terms of Registration with SFFMC Etiquette document: https://docs.google.com/document/d/1SFptLv4V84lso9yqTWT49s__W3elnUQn/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true

**Comment by willfulbard** [comment]
Where is this to be replace from?  Please be more specific

**Comment by bloomingbooks** [comment]
At bottom of form, before Continue to Payment, replace By submitting this form, you agree to the [Terms of Registration](https://docs.google.com/document/d/1pq2i2rHpHnsoB8kqtpH7FFn50JA-XELaRRMHh4hdTFg/edit?usp=sharing)

WITH

By submitting this form, you agree to the [SFFMC Etiquette document] https://docs.google.com/document/d/1SFptLv4V84lso9yqTWT49s__W3elnUQn/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true
