### ISSUE TITLE
Camp Harmony: Link to Registration rates

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#420]
https://docs.google.com/spreadsheets/d/1UvAbUg8KC5nCQWtYNe_V5Jecb3OtHC3lrn-_nBYHKxI/edit?usp=sharing

Under LODGING
Click here [link] to see 2023-24 rates for lodging (all prices include meals)

**Comment by willfulbard** [comment]
I can't add this under Lodging, but I added it to the top under a new heading

**Comment by bloomingbooks** [comment]
ok
