### ISSUE TITLE
Lark Campout: Revert rebranding "JugLark" => "Lark Campout"

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#422]
Alex and Meghan both don't really like JugLark, per discussion over the phone I'm going to revert the rebranding and perhaps in the future we will change the name if we get more agreement around it.

**Comment by millerlark** [comment]
Previous announcements have said Lark Campout and it is that way in the budget, in quickbooks etc... I am going to have the registration announcement letter say "Lark Campout at Jughandle Farm". You don't need to say that on the acutal reg form, but I am hoping that will help a little. Alex and I have been discussing this, but we think that if there is a change, it should be for next year.
