### ISSUE TITLE
Camp Harmony report: linens

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#448]
Linens requested:
Total number requested for Village 1, 5, 6 and 7 & Wellness center
Total requested for Village 2 (because these are queen sheets, I need them separated out)

**Comment by willfulbard** [comment]
Partially complete:

https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=7

**Comment by willfulbard** [comment]
@bloomingbooks please review the current report and let me know if I can close this issue.

**Comment by bloomingbooks** [comment]
Looks great -- ok to close this ticket.
