### ISSUE TITLE
Camp Harmony report: Camperships awarded

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#451]
Last name           Campership awarded
[last name]         $[campership awarded]

Total campership funds awarded:  [total of all campership funds awarded]

**Comment by willfulbard** [comment]
I have a preliminary report for this.  I'm working on a better one:

https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=3

**Comment by willfulbard** [comment]
The report is done
