### ISSUE TITLE
Camp Harmony: voucher isn't working like I think it should

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#457]
Jason Pollack owed $294; 2 semi-private nights minus $100 campership.  I believe he paid by check: $294.  He now owes an additional $20 for a single room.  I clicked voucher and entered -20, which I thought would add $20 to his bill, for a total of $314. Instead, it shows paid $274.
Halp.

**Comment by willfulbard** [comment]
You are correct, vouchers work like currency for a payment, so negative payments adds money to your total.  Add a payment of $40 in voucher, and that should balance it out.
