### ISSUE TITLE
Camp Harmony report: total paid for registration

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#460]
Ellen says: the payment report is not detailed enough. It shows just the total amount paid, which will include any campership donations. I want to separate campership donations from registration.
We can get total paid for linens from the report showing how many linens we need.

**Comment by willfulbard** [comment]
I have a campership donation report, ask Ellen if this works: https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=4

**Comment by willfulbard** [comment]
Please see if the latest version works

**Comment by bloomingbooks** [comment]
Looks great! Closing ticket.
