### ISSUE TITLE
Camp Harmony: housing report

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#478]
I'm going to need a report sorted in order by housing:
Village 1; cabin 100A; Last name, first name; xxx Thurs Fri Sat xxx
Village 1; cabin 100A; Last name, first name; Wed Thurs Fri xxx xxx
Village 1; cabin 100B; Last name, first name; Wed Thurs Fri Sat Sun
etc.

If it can fit on one page and the columns for housing can all line up, that would be the best, but just having the info will be very helpful.  I need this by Dec. 12. Have to submit reports to Newman on Dec. 13.
Thank you!

**Comment by bloomingbooks** [comment]
DEADLINE:  I need this report by Dec. 12

**Comment by willfulbard** [comment]
@bloomingbooks Please review https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=10

And let me know if that works
