### ISSUE TITLE
Camp Harmony: balance due has too many decimals for some users

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#483]
Showing waaaay too many numbers after the decimal point, and the math has stopped working!

**Comment by willfulbard** [comment]
Nomi Harris is example in camp harmony

**Comment by bloomingbooks** [comment]
Search Nomi Harris under Registrations, look at Payments tab, look at Balance due.

**Comment by bloomingbooks** [comment]
closing this because it has not become a problem this year.
