### ISSUE TITLE
Camp Harmony report: names and emails

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#485]
We need this to contact people for chores and also to get musicians for the dances. Deadline: would be helpful to have by Dec. 14/15.

Alpha order by last name including email address and days at camp:

Last name, first name    email       Wed Thurs Fri Sat Sun

**Comment by willfulbard** [comment]
@bloomingbooks  - review please https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=11
