### ISSUE TITLE
Camp Harmony: report of food allergies

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#488]
I need all the text from the "Additional dietary restrictions or allergies" field with Name of camper and days of attendance:

Yael Schy       xxx Thurs   Fri    Sat  xxx  xxx       All the text from the dietary restrictions field

Sorry I only just realized this info isn't included in the dietary report. I need this info asap.
Thanks.

**Comment by willfulbard** [comment]
@bloomingbooks See https://harmonyreg.sffmc.org/admin/organization/1/event/1/reports?reportId=12

**Comment by bloomingbooks** [comment]
Perfect! I've sent in the info. Thanks again.
