### ISSUE TITLE
Campers switching position error

### ISSUE THREAD

**Issue by millerlark** [camphoric/camphoric#515]
Some campers have switched position in the database. It now lists some guest campers as the first camper instead of second. This affects totals for crew and instructors when the guest is a minor or is not getting meals because it is counting the guest as the discounted camper instead of the crew member or instructor. My guess is that the registration system at some point re-ordered campers in individual registration groups in alpha order.

**Comment by willfulbard** [comment]
I'm going to try make sure that campers are always ordered by insert ID, hopefully this midigates and/or solves the problem.

**Comment by willfulbard** [comment]
fixed in #516
