### ISSUE TITLE
Corrections to Camp Harmony registration form

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#529]
Replace Covid and cancellations policy link with: https://docs.google.com/document/d/134EIqyOK5xXswp5EEbNRw0gBrr-TvUsh/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true

After Phone number, add 2 fields:
License plate: Provide the license plate for the car you will be driving to camp:

Cell phone number: If we need to reach you during camp:

Move "LODGING: click here to see current rates" line to be above "Select your lodging preference" on form

Lodging drop-down preferences:
For Lodge add (includes linens. Preference given to campers staying for full camp)

When will you attend:
(need to correct days of week on the boxes)
Friday Dec. 27
Saturday Dec. 28
Sunday Dec. 29
Monday Dec. 30
Tuesday Dec. 31

**Comment by willfulbard** [comment]
In the future, please separate these out into separate issues.

**Comment by willfulbard** [comment]
Move "LODGING: click here to see current rates" line to be above "Select your lodging preference" on form

cannot be done

**Comment by willfulbard** [comment]
Lodging drop-down preferences:
For Lodge add (includes linens. Preference given to campers staying for full camp)

This cannot be done unless you want this to show up as the name for lodge in all reports

**Comment by willfulbard** [comment]
Cell phone number: If we need to reach you during camp:

Are you saying you want BOTH phone and cell phone?
