### ISSUE TITLE
Camp Harmony: add checkbox for Etiquette document

### ISSUE THREAD

**Issue by bloomingbooks** [camphoric/camphoric#538]
Committee member wants campers to check a box saying they have read and agree to the etiquette doc.

Change

By submitting this form, you agree to the [SFFMC Etiquette document](https://docs.google.com/document/d/1SFptLv4V84lso9yqTWT49s__W3elnUQn/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true)

to

[Checkbox] I have read and agree to the [SFFMC Etiquette document](https://docs.google.com/document/d/1SFptLv4V84lso9yqTWT49s__W3elnUQn/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true)

**Comment by willfulbard** [comment]
The checkbox widget is not setup to have links or descriptions, this would delay registration opening by a week, so I'm skipping this for now.

**Comment by bloomingbooks** [comment]
Ok. In that case change to

By submitting this form, I affirm that I have read and agree to the [SFFMC Etiquette document](https://docs.google.com/document/d/1SFptLv4V84lso9yqTWT49s__W3elnUQn/edit?usp=sharing&ouid=112175546889387017762&rtpof=true&sd=true)
