### ISSUE TITLE
Admin interface code

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#59]
I was thinking about our app front-end, and I realize that we're going to need at least two separate entry points: 

1. the registration interface for unregistered campers
1. the administration interface for admins

I think there are a couple solutions to this problem that I would consider:

## Solution 1: Create another react-create-app

I think we'll probably want to be sharing code between the registration and admin sections, so I'd rather not do this.

## Solution 2: A single page app with an authenticated and non-authenticated section

Simply have a separate admin section that you can access via react-router.  I'd also rather not do this since I don't think this has very good security implications, but it is the simplest solution and won't require us to eject our app.

## Solution 3: The non-ejecting, but still two apps solution

We could split the one page we have into two separate pages.  I would rather not keep it as a single page for security reasons, but here is a blog post with a possible solution:

https://blog.logrocket.com/multiple-entry-points-in-create-react-app-without-ejecting/

## Solution 4: Eject the app and have two entry points set up via webpack

This would be AFAIK, the traditional solution to this problem.

**Comment by evinism** [comment]
My inclination originally was to go for #2. I'm having trouble coming up with any negative security implications to that that aren't indicative of a much larger problem.  The one thing I'd want to be wary of is initial bundle size, but hopefully CRA has good tools to combat that w/ lazy loading JS.

**Comment by willfulbard** [comment]
@evinism - I had no idea about [reacts code-splitting](https://reactjs.org/docs/code-splitting.html#import)!  I should really be keeping current. I think you're right, and @brsaylor, @toolgirl, and I talked about it in our meeting today.  We decided that #2 makes a lot of sense based on your recommendation.  The bundle size may be more, but that doesn't affect security anyway, and probably won't add a HUGE amount to the initial bundle size.

If we see that the initial bundle size is affected, we can always fix it as a future optimization, but it makes sense not to count it as a release blocker.

**Comment by evinism** [comment]
Fantastic!

**Comment by willfulbard** [comment]
I have confirmed that codesplitting works as we hoped!

See this PR: https://github.com/camphoric/camphoric/pull/61

And this output:

![codesplitting](https://user-images.githubusercontent.com/15619556/94349147-d2174700-fff6-11ea-818f-30b00357449a.gif)
