### ISSUE TITLE
Implement invitations for special registration types 

### ISSUE THREAD

**Issue by toolgirl** [camphoric/camphoric#62]
Create a system for a secure way to register special types of registrants that correspond to different kinds of staff that pay different amounts. You get a special link you get a special form.

Expands on #23 https://github.com/camphoric/camphoric/issues/23#issuecomment-636268357

**Comment by toolgirl** [comment]
Thoughts about invitations: 
- invitations have email address of recipient
- id of sender
- sending timestamp
- invitation (unique) code
- timestamp when redeemed
- id of redeeming registration
- registration type (kitchen/management/etc.) part of the model
- default vs invitation code
- needs way to be cancelled (soft delete)

Error message: One generic error message on any type of invalid invitation code

**Comment by toolgirl** [comment]
# Proposal

## Overview of user experience:
The administrator creates an invitation by entering an email address, choosing a type of registration and sending it. The prospective registrant receives the email, which includes a link to registration form with an invitation code. This code is unique and can only be redeemed once. it is not time limited but can be cancelled by the administrator. The prospective registrant clicks the link and is directed to a form that reflects their registration type and any pricing differences from the default registration. 

## Implementation: 

- [ ] Create RegistrationType model
    - event
    - name
    - label
    - invitation_email_template

- [ ] Add RegistrationType field to Registration model 

- [ ] Include RegistrationType into input for price calculations

- [ ] Create Invitation model
    - will inherit from Timestamp model
    - registration (initinally null, populated when invitation is redeemed)
    - registration_type

**Comment by brsaylor** [comment]
Also need to update client-side pricing calculations to include registration_type

**Comment by brsaylor** [comment]
Also, update the registration form:
- show the invitation (or invitationError)
- include the invitation in the POST data

**Comment by brsaylor** [comment]
I think the API and registration form changes are done.

# Admin interface

To tie everything together, the admin app need page to manage RegistrationTypes and Invitations, as well as send invitations. Proposal for this page:

- list of existing invitations (`GET /api/invitations/`)
- "send" button for each invitation which will email the invitation (`POST /api/invitations/{invitation.id}/send`)
- "edit" button for each invitation which would show an edit form (`PUT /api/invitations/{invitation.id}/`)
- maybe a "delete" button (`DELETE /api/invitations/{invitation.id}/`)
- form to create a new invitation (`POST /api/invitations/`)

The create/edit form should make these fields editable (others are set automatically):
- `recipient_name`
- `recipient_email`
- `expiration_time`
- `registration_type`

`registration_type` should allow adding/editing RegistrationTypes via `/api/registrationtypes/*` -- GET to list, POST to create, PUT to edit, DELETE to delete

[fields for RegistrationType](https://github.com/camphoric/camphoric/blob/c8c03942b8a859675a4ffa06416a97e81205c9de/server/camphoric/models.py#L87)

[fields for Invitation](https://github.com/camphoric/camphoric/blob/c8c03942b8a859675a4ffa06416a97e81205c9de/server/camphoric/models.py#L118)
