### ISSUE TITLE
Install and implement django-rest-framework-simplejwt

### ISSUE THREAD

**Issue by willfulbard** [camphoric/camphoric#69]
After looking through the current state of web auth, the best practice seems to be to have:

1. A httponly cookie which is set as the auth token
2. A refresh token which can be used to get a new httponly cookie

This looks like the way to do that:

- https://django-rest-framework-simplejwt.readthedocs.io/en/latest/
- https://simpleisbetterthancomplex.com/tutorial/2018/12/19/how-to-use-jwt-authentication-with-django-rest-framework.html

**Comment by toolgirl** [comment]
Further research shows me that httpOnly cookie authentication has not been implemented in simplejwt. There is an open PR here: https://github.com/SimpleJWT/django-rest-framework-simplejwt/pull/157
The current system is keeping the token in local storage. Should I look into other cookie based authentication?

**Comment by toolgirl** [comment]
It looks like with out of the box packages we can't do exactly what is suggested here. We can do cookie authentication, or jwt but not both. This article might have an answer: https://medium.com/swlh/django-rest-framework-and-spa-session-authentication-with-docker-and-nginx-aa64871f29cd

**Comment by willfulbard** [comment]
I think cookie auth is what I'm after - and I don't think we really need jwt auth for now.

I'll do the less secure thing and put the auth cookie into local storage until we figure out a good lib.  That should at least let us move forward for now, and I'll try to abstract the auth parts so that we can easily move to the Correct Way™️ when we get that figured out.

Thanks so much for looking into this @toolgirl! sorry I was wrong about the capabilities of the lib.
